# Generated by Django 4.0 on 2021-12-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('one', models.CharField(max_length=20)),
                ('two', models.CharField(max_length=20)),
                ('tree', models.CharField(max_length=20)),
                ('four', models.CharField(max_length=20)),
            ],
        ),
    ]
