# Generated by Django 4.0 on 2021-12-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_questions_cat_alter_questions_four_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
