# Generated by Django 4.0 on 2021-12-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_cat_alter_questions_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.BooleanField(default=False, verbose_name='answer')),
                ('two', models.BooleanField(default=False, verbose_name='answer')),
                ('tree', models.BooleanField(default=False, verbose_name='answer')),
                ('four', models.BooleanField(default=False, verbose_name='answer')),
            ],
        ),
    ]
