# Generated by Django 4.0 on 2021-12-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='four',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='one',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='two',
        ),
        migrations.AddField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='title',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
