# Generated by Django 4.0 on 2021-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_alter_answers_question_alter_questions_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='reportـcard',
            name='score',
            field=models.IntegerField(),
        ),
    ]
