# Generated by Django 4.0 on 2021-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_rename_result_user_answers_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_answers',
            name='is_correct',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
