# Generated by Django 4.0 on 2021-12-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_alter_user_answers_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='user_answers',
            name='question',
        ),
        migrations.RemoveField(
            model_name='user_answers',
            name='user',
        ),
        migrations.DeleteModel(
            name='reportـcard',
        ),
        migrations.DeleteModel(
            name='User_answers',
        ),
    ]
