# Generated by Django 4.0 on 2021-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_remove_user_answers_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exsam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soalat', models.JSONField()),
                ('exsam_id', models.IntegerField()),
            ],
        ),
    ]
